name: space battle test

on:
  push:
    branches: ["solution_upgrade"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ./spacebattle/SpaceBattleLib

      - name: Build
        run: dotnet build ./spacebattle/SpaceBattleLib --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test
        run: cd spacebattle && cd SpaceBattleTest && dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  
